help:
	@echo "train -- train model"
	@echo "run -- run trained model"
	@echo "clean -- remove dataset for testing"

train:
	python3 detector_trainer.py

run:
	python3 detector.py

clean:
	rm -r dataset
	rm -r runs
