ROOT:=$(git rev-parse --git-dir)

# TODO: add script to clone deep_sort, get detections and network weights from google drive + unzip them

track:
	cd $(ROOT) && python3 notebooks/tracking/tracker.py
